version: '3.8'
services:
  rust_service:
    build:
      context: ./rust_service
      dockerfile: Dockerfile
    ports:
      - "3030:3030"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - rust_service
