name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      rust_service:
        image: rust:latest
        ports:
          - 3030:3030

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust service
        run: |
          cd rust_service
          cargo build --release

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Docker Images
        run: |
          # Build Rust service image
          docker build -t ghcr.io/YashzAlphaGeek/Rust-React-The-Dockerized-Adventure/rust_service:latest ./rust_service

          # Build Frontend image
          docker build -t ghcr.io/YashzAlphaGeek/Rust-React-The-Dockerized-Adventure/frontend:latest ./frontend

      - name: Log in to GitHub Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u <GITHUB_USERNAME> --password-stdin

      - name: Push Docker Images
        run: |
          docker push ghcr.io/<GITHUB_USERNAME>/<REPO_NAME>/rust_service:latest
          docker push ghcr.io/<GITHUB_USERNAME>/<REPO_NAME>/frontend:latest